- LICENSE
- README.md
Update LICENSE & README files prior to cutting first release & sharing with customers
> Updates to LICENSE & README files

- plugin.json
- server/legalhold/legal_hold.go
- server/model/channel.go
- server/model/export.go
- server/model/index.go
- server/model/index_test.go
- server/store/sqlstore/legal_hold.go
This includes:
* Team name, id, display name
* Channel name, id, display name and type
* Basic LegalHold details (name, id, display name, start time, last executed at time)
Also adds TeamID to CSV files of messages.
This is to make the HTML processed version more human-friendly.
Fixes #22
> Add additional metadata to index.

- webapp/webpack.config.js
When the plugin's webapp bundle is loaded in the frontend, we hit this error that makes the plugin fail to load. Some libraries expect `process.env.NODE_ENV` to be available during runtime. By default, attempting to access this property results in a null pointer because `process` is not normally defined in the context of the browser.
This PR configures a webpack plugin that fills in the `process.env.NODE_ENV` variable in the bundle, to match the value at compilation time. See more here https://stackoverflow.com/a/64553486
> Fix process.env frontend issue

- server/plugin.go
Check for a valid enterprise licence on plugin activation.
Fixes #5
> fix: check for enterprise licence on plugin activation

- README.md
Adds a section in the README specifying potential issues with large legal holds and low timeout settings.
Closes #44
> docs: note on timeout issues for large downloads

- processor/cmd/root.go
Cleans up the `tempPath` after the `Process` call is done.
Fixes #25
> fix: clean up temporary directory on exit of export processor

- webapp/src/components/update_legal_hold_form/update_legal_hold_form.tsx
Make the end date field not required to avoid validation errors when the form can be successfully submitted.
Closes #56
> fix: end date not required when updating legal hold

- server/legalhold/legal_hold.go
- server/model/legal_hold.go
- server/store/sqlstore/legal_hold.go
- server/store/sqlstore/legal_hold_test.go
- server/store/sqlstore/testhelper.go
- webapp/src/components/create_legal_hold_form.scss
- webapp/src/components/create_legal_hold_form.tsx
- webapp/src/components/update_legal_hold_form/update_legal_hold_form.tsx
- webapp/src/types/index.d.ts
Adds a new option to legal holds to avoid storing data from public channels
Closes #55
> feat: allow excluding public channels from a legal hold

- README.md
There was a feature added for demoing the plugin, to run the plugin's scheduled job on demand, rather than waiting until the next run of the job https://github.com/mattermost/mattermost-plugin-legal-hold/pull/43. In order to surface this available functionality for development and testing purposes, this PR explains this feature in the README.
Context for this PR https://github.com/mattermost/mattermost-plugin-legal-hold/issues/69#issuecomment-2176461581
> Explain in README how to run the legal hold job on demand

- server/model/legal_hold.go
- server/model/legal_hold_test.go
On MM cloud servers, this plugin returned no data when downloading the legal hold data from the UI. It produces an empty zip file as noted in https://github.com/mattermost/mattermost-plugin-legal-hold/issues/69
Upon debugging this, I found that having parentheses in the folder path makes it incompatible with the cloud server's file backend. I believe this has to do with this server's usage of `bifrost` https://github.com/mattermost/bifrost. In the case of using the parenthese (i.e. before the changes in this PR), I've verified that the files are correctly written and read from, though the call to `p.FileBackend.ListDirectoryRecursively(legalHold.BasePath())` [here](https://github.com/mattermost/mattermost-plugin-legal-hold/blob/0afda796c5a9d13bf510e9b987356eadde8efdc1/server/api.go#L236) …
> Remove parentheses from legal hold folder path to work on MM Cloud servers

- .github/workflows/ci.yml
- Makefile
This PR adds support for building the processor via the `make dist` or `make processor` commands.  It also removes building the plugin for non-supported environments.
NONE
> Build processor via makefile

- plugin.json
Bumps plugin version to 0.4.0 to match release:  https://github.com/mattermost/mattermost-plugin-legal-hold/releases/tag/v0.4.0
NONE
> Bump version to 0.4.0-alpha

- processor/parse/legal_holds.go
Modifies processor folder name check to match #74 
Fixes #80
> fix: check for correct path name inside legal-hold zip file

- webapp/src/components/legal_hold_table/legal_hold_table.tsx
- webapp/src/components/legal_holds_setting.tsx
- webapp/src/components/mattermost-webapp/input/input.tsx
- webapp/src/components/update_legal_hold_form/update_legal_hold_form.tsx
The LegalHoldTable component was missing a dependency array in a `useEffect` hook.  This caused the hook to be called on every render.  
Additional dependencies were added to other components based on linter errors.
Fixes https://github.com/mattermost/mattermost-plugin-legal-hold/issues/85
> GH-85 Include dependencies array in useEffect for all components

- webapp/src/components/admin_console_settings/secret_text_setting.tsx
- There was an issue in the custom plugin setting code due to which the S3 key was not getting store in the config and hence the S3 bucket was not getting connected
Fixes: https://hub.mattermost.com/partners/pl/kwu4ef1kepgs7djnbibowrku3h
> Fix S3 bucket connection issue

- Makefile
- server/legalhold/legal_hold_test.go
- server/store/sqlstore/legal_hold.go
- server/store/sqlstore/testhelper.go
- server/utils/testcontainers.go
This incidentally fixes a bug on MySQL with the feature to exclude public channels from the Legal Hold.
Fixes #77
> Run the tests on MySQL as well as Postgres.

- server/api.go
- server/model/legal_hold.go
- server/model/legal_hold_test.go
- server/store/kvstore/legal_hold.go
- server/store/kvstore/legal_hold_test.go
- If the legal hold is created/updated with the exclude public channels disabled (including public channel data) a check is made to ensure that compliance export is enabled
- Added validation in the API layer
- Removed validation from the KVStore layer (since it's redundant and is not checking what we think it is)
- Added a validation for dates (`StartDate < EndDate`)
https://mattermost.atlassian.net/browse/MM-59830
> fix: including public channels should check for compliance settings

- server/jobs/legal_hold_job.go
Changes the log output of the legal hold processor job to display only the ID and the Name of the legal hold being run, instead of the representation of the entire legal hold inside the log message attribute.
https://mattermost.atlassian.net/browse/MM-59853
> chore: change log output

- server/api.go
- webapp/src/client.ts
- Changes the API path to `/api/v1/legalholds` (from `/api/v1/legalhold`)
- Changes the `.../update` endpoint to use `PUT` instead of `POST`, removing the `/update` in the path.
https://mattermost.atlassian.net/browse/MM-59829
> chore: use put instead of post for update

- plugin.json
Bump version number to 1.0.1 since the `make major` did not do it automatically for 1.0
NONE
> Bump version to 1.0.1

- server/plugin.go
- Disable AWS settings if AWS config is invalid
1. Enable S3 settings and add a invalid config
2. Save the config
3. Refresh the page, the S3 settings should be disabled.
Fixes #94
> [GH-94] Disable S3 settings if AWS config is invalid

- README.md
Developers docs are not needed for this plugin's README and create confusion for customers.
NONE
> Remove developer docs from README

- e2e/playwright/README.md
- e2e/playwright/tests/create_legal_hold.spec.ts
- webapp/src/components/users_input/users_input.jsx
Deactivated users were not appearing in the search results. I tested the functionality to see if the actual job works with deactivated users and from what I can tell it's fine. I don't have intimate knowledge of how the plugin works though.
Also fixed the failing e2e tests.
https://mattermost.atlassian.net/browse/MM-62099
> Surface deactivated users in the search input & E2E fixes

- .github/workflows/playwright.yml
- e2e/playwright/tests/create_legal_hold.spec.ts
- e2e/playwright/tests/release_legal_hold.spec.ts
Playwright tests [were failing](https://github.com/mattermost/mattermost-plugin-legal-hold/actions/runs/13282340411/job/37083224510?pr=134) because the minimum postgresql version is 13 and we had 12 and updated tests to follow changes in the e2e support library.
> fix: upgrade postgresql for playwright tests

- e2e/playwright/tests/test.setup.ts
This fixes a change in the trial request which now requires the country parameter to be set.
> test(e2e): send company_country when requesting trial license
